export enum queryKeys {
  // IMBY
  GET_PROJECTS = 'GET_PROJECTS',
  GET_PLANTS = 'GET_PLANTS',
  GET_ASSETS = 'GET_ASSETS',
  GET_MEASUREMENTS_BY_ASSET_GUID = 'GET_MEASUREMENTS_BY_ASSET_GUID',
  GET_MEASUREMENTS_BY_PLANT_GUID = 'GET_MEASUREMENTS_BY_PLANT_GUID',
  GET_MEASUREMENT_VERSIONS_BY_MEASUREMENT_GUID = 'GET_MEASUREMENT_VERSIONS_BY_MEASUREMENT_GUID',
  GET_MEASUREMENT_VERSIONS = 'GET_MEASUREMENT_VERSIONS',
  GET_MEASUREMENT_VALUES = 'GET_MEASUREMENT_VALUES',
  GET_MEASUREMENT_DTO_VALUES = 'GET_MEASUREMENT_DTO_VALUES',
  GET_FIRST_VALUE = 'GET_FIRST_VALUE',
  GET_LATEST_VALUE = 'GET_LATEST_VALUE',

  // USERS
  GET_USER_BY_ID = 'GET_USER_BY_ID',

  // TEMPLATES
  GET_TEMPLATES = 'GET_TEMPLATES',
  GET_TEMPLATE_BY_ID = 'GET_TEMPLATE_BY_ID',

  // DASHBOARDS
  GET_DASHBOARDS = 'GET_DASHBOARDS',
  GET_DASHBOARDS_BY_TEMPLATE_ID = 'GET_DASHBOARDS_BY_TEMPLATE_ID',
  GET_DASHBOARD_BY_ID = 'GET_DASHBOARD_BY_ID',
  GET_DASHBOARD_BY_SHARE_ID = 'GET_DASHBOARD_BY_SHARE_ID',
}
